# Base configs
baseurl: "http://www.naxgyumi.com"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Nax Gyumi"
subtitle: "See the world through my eyes!"
author: "Nax Gyumi"
header:
 title: "Photography"
 subtitle: "by Nax Gyumi"
footer:
 name: "Hey there, my name is Nax Gyumi"
 bio: "To see, to learn."
 github: ""
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
# 小红书: 了更
#   instagram: "https://www.instagram.com/ram_patra"
#   dribbble: "https://dribbble.com/rampatra"
#   linkedin: "https://in.linkedin.com/in/ram-patra"
#   github: "https://www.github.com/rampatra"
